#!/usr/bin/python3

import sys, socket

if __name__ == '__main__':
    args = sys.argv[1:]
    try: 
        udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sent_data = ' '.join(args[2:])
        udp.sendto(sent_data.encode(), (args[0], int(args[1])))
        print(f"{sent_data} DATA SENT TO DESTINATION")
    except socket.error as e:
        print(f"ERROR OCCURRED: {str(e)}")
