#!/usr/bin/python3

import sys, socket

if __name__ == '__main__':
    rcv_ip, rcv_port = sys.argv[1].split(':')
    try: 
        udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        if(rcv_ip.endswith('255')): 
            udp.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        udp.bind((rcv_ip, int(rcv_port)))
        data = None
        while data != 'EXIT': 
            data = udp.recv(1024).decode()
            print(data, flush=True)
    except Exception as e:
        print(f"ERROR OCCURRED: {str(e)}", flush=True)