#!/usr/bin/python3

import sys, socket

if __name__ == '__main__':
    rcv_ip, rcv_port = sys.argv[1], int(sys.argv[2])
    try: 
        udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        udp.bind((rcv_ip, rcv_port))
        data = None
        while data != 'EXIT': 
            data = udp.recv(1024).decode()
            print(data, flush=True)
    except Exception as e:
        print(f"ERROR OCCURRED: {str(e)}", flush=True)